// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: career_stats.sql

package db

import (
	"context"
	"database/sql"
)

const getAllPlayerNames = `-- name: GetAllPlayerNames :many
SELECT DISTINCT "PLAYER_ID", "PLAYER_NAME"
FROM career_stats
ORDER BY "PLAYER_NAME" ASC
`

type GetAllPlayerNamesRow struct {
	PLAYERID   int64          `json:"PLAYER_ID"`
	PLAYERNAME sql.NullString `json:"PLAYER_NAME"`
}

func (q *Queries) GetAllPlayerNames(ctx context.Context) ([]GetAllPlayerNamesRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllPlayerNames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllPlayerNamesRow
	for rows.Next() {
		var i GetAllPlayerNamesRow
		if err := rows.Scan(&i.PLAYERID, &i.PLAYERNAME); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlayerByID = `-- name: GetPlayerByID :one
SELECT DISTINCT "PLAYER_ID", "PLAYER_NAME"
FROM career_stats
WHERE "PLAYER_ID" = $1
`

type GetPlayerByIDRow struct {
	PLAYERID   int64          `json:"PLAYER_ID"`
	PLAYERNAME sql.NullString `json:"PLAYER_NAME"`
}

func (q *Queries) GetPlayerByID(ctx context.Context, playerID int64) (GetPlayerByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getPlayerByID, playerID)
	var i GetPlayerByIDRow
	err := row.Scan(&i.PLAYERID, &i.PLAYERNAME)
	return i, err
}

const getPlayerCareerPath = `-- name: GetPlayerCareerPath :many
SELECT 
    "TEAM_ABBREVIATION",
    "SEASON_ID",
    "PLAYER_AGE",
    "GP",
    "MIN",
    "FGM",
    "FGA",
    "FG_PCT",
    "FG3M",
    "FG3A",
    "FG3_PCT",
    "FTM",
    "FTA",
    "FT_PCT",
    "OREB",
    "DREB",
    "REB",
    "AST",
    "STL",
    "BLK",
    "TOV",
    "PF",
    "PTS"
FROM career_stats
WHERE "PLAYER_ID" = $1
ORDER BY "SEASON_ID" ASC
`

type GetPlayerCareerPathRow struct {
	TEAMABBREVIATION sql.NullString  `json:"TEAM_ABBREVIATION"`
	SEASONID         string          `json:"SEASON_ID"`
	PLAYERAGE        sql.NullFloat64 `json:"PLAYER_AGE"`
	GP               sql.NullInt64   `json:"GP"`
	MIN              sql.NullInt64   `json:"MIN"`
	FGM              sql.NullInt64   `json:"FGM"`
	FGA              sql.NullInt64   `json:"FGA"`
	FGPCT            sql.NullFloat64 `json:"FG_PCT"`
	FG3M             sql.NullInt64   `json:"FG3M"`
	FG3A             sql.NullInt64   `json:"FG3A"`
	FG3PCT           sql.NullFloat64 `json:"FG3_PCT"`
	FTM              sql.NullInt64   `json:"FTM"`
	FTA              sql.NullInt64   `json:"FTA"`
	FTPCT            sql.NullFloat64 `json:"FT_PCT"`
	OREB             sql.NullInt64   `json:"OREB"`
	DREB             sql.NullInt64   `json:"DREB"`
	REB              sql.NullInt64   `json:"REB"`
	AST              sql.NullInt64   `json:"AST"`
	STL              sql.NullInt64   `json:"STL"`
	BLK              sql.NullInt64   `json:"BLK"`
	TOV              sql.NullInt64   `json:"TOV"`
	PF               sql.NullInt64   `json:"PF"`
	PTS              sql.NullInt64   `json:"PTS"`
}

func (q *Queries) GetPlayerCareerPath(ctx context.Context, playerID int64) ([]GetPlayerCareerPathRow, error) {
	rows, err := q.db.QueryContext(ctx, getPlayerCareerPath, playerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPlayerCareerPathRow
	for rows.Next() {
		var i GetPlayerCareerPathRow
		if err := rows.Scan(
			&i.TEAMABBREVIATION,
			&i.SEASONID,
			&i.PLAYERAGE,
			&i.GP,
			&i.MIN,
			&i.FGM,
			&i.FGA,
			&i.FGPCT,
			&i.FG3M,
			&i.FG3A,
			&i.FG3PCT,
			&i.FTM,
			&i.FTA,
			&i.FTPCT,
			&i.OREB,
			&i.DREB,
			&i.REB,
			&i.AST,
			&i.STL,
			&i.BLK,
			&i.TOV,
			&i.PF,
			&i.PTS,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRandomPlayer = `-- name: GetRandomPlayer :one
SELECT DISTINCT "PLAYER_ID", "PLAYER_NAME"
FROM career_stats
ORDER BY RANDOM()
LIMIT 1
`

type GetRandomPlayerRow struct {
	PLAYERID   int64          `json:"PLAYER_ID"`
	PLAYERNAME sql.NullString `json:"PLAYER_NAME"`
}

func (q *Queries) GetRandomPlayer(ctx context.Context) (GetRandomPlayerRow, error) {
	row := q.db.QueryRowContext(ctx, getRandomPlayer)
	var i GetRandomPlayerRow
	err := row.Scan(&i.PLAYERID, &i.PLAYERNAME)
	return i, err
}
