// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: daily_game.sql

package db

import (
	"context"
	"time"
)

const createDailyGame = `-- name: CreateDailyGame :one
INSERT INTO daily_game (player_id, game_date)
VALUES ($1, $2)
RETURNING id, player_id, game_date, created_at
`

type CreateDailyGameParams struct {
	PlayerID int32     `json:"player_id"`
	GameDate time.Time `json:"game_date"`
}

func (q *Queries) CreateDailyGame(ctx context.Context, arg CreateDailyGameParams) (DailyGame, error) {
	row := q.db.QueryRowContext(ctx, createDailyGame, arg.PlayerID, arg.GameDate)
	var i DailyGame
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.GameDate,
		&i.CreatedAt,
	)
	return i, err
}

const getDailyGameByID = `-- name: GetDailyGameByID :one
SELECT id, player_id, game_date, created_at FROM daily_game
WHERE id = $1
`

func (q *Queries) GetDailyGameByID(ctx context.Context, id int32) (DailyGame, error) {
	row := q.db.QueryRowContext(ctx, getDailyGameByID, id)
	var i DailyGame
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.GameDate,
		&i.CreatedAt,
	)
	return i, err
}

const getTodayGame = `-- name: GetTodayGame :one
SELECT id, player_id, game_date, created_at FROM daily_game
WHERE game_date = CURRENT_DATE
`

func (q *Queries) GetTodayGame(ctx context.Context) (DailyGame, error) {
	row := q.db.QueryRowContext(ctx, getTodayGame)
	var i DailyGame
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.GameDate,
		&i.CreatedAt,
	)
	return i, err
}
