// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: guesses.sql

package db

import (
	"context"
	"time"
)

const createGuess = `-- name: CreateGuess :one
INSERT INTO guesses (user_id, daily_game_id, guess, is_correct)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, daily_game_id, guess, is_correct, created_at
`

type CreateGuessParams struct {
	UserID      int32  `json:"user_id"`
	DailyGameID int32  `json:"daily_game_id"`
	Guess       string `json:"guess"`
	IsCorrect   bool   `json:"is_correct"`
}

func (q *Queries) CreateGuess(ctx context.Context, arg CreateGuessParams) (Guess, error) {
	row := q.db.QueryRowContext(ctx, createGuess,
		arg.UserID,
		arg.DailyGameID,
		arg.Guess,
		arg.IsCorrect,
	)
	var i Guess
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DailyGameID,
		&i.Guess,
		&i.IsCorrect,
		&i.CreatedAt,
	)
	return i, err
}

const getGuessCount = `-- name: GetGuessCount :one
SELECT COUNT(*) FROM guesses
WHERE user_id = $1
AND daily_game_id = $2
`

type GetGuessCountParams struct {
	UserID      int32 `json:"user_id"`
	DailyGameID int32 `json:"daily_game_id"`
}

func (q *Queries) GetGuessCount(ctx context.Context, arg GetGuessCountParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getGuessCount, arg.UserID, arg.DailyGameID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getGuessesByUserAndGame = `-- name: GetGuessesByUserAndGame :many
SELECT id, user_id, daily_game_id, guess, is_correct, created_at FROM guesses
WHERE user_id = $1
AND daily_game_id = $2
ORDER BY created_at ASC
`

type GetGuessesByUserAndGameParams struct {
	UserID      int32 `json:"user_id"`
	DailyGameID int32 `json:"daily_game_id"`
}

func (q *Queries) GetGuessesByUserAndGame(ctx context.Context, arg GetGuessesByUserAndGameParams) ([]Guess, error) {
	rows, err := q.db.QueryContext(ctx, getGuessesByUserAndGame, arg.UserID, arg.DailyGameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Guess
	for rows.Next() {
		var i Guess
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DailyGameID,
			&i.Guess,
			&i.IsCorrect,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserGameHistory = `-- name: GetUserGameHistory :many
SELECT
    dg.id as game_id,
    dg.game_date,
    COALESCE(bool_or(g.is_correct), false) as won,
    COUNT(g.id) as guesses_used
FROM daily_game dg
JOIN guesses g ON g.daily_game_id = dg.id AND g.user_id = $1
GROUP BY dg.id, dg.game_date
ORDER BY dg.game_date DESC
`

type GetUserGameHistoryRow struct {
	GameID      int32       `json:"game_id"`
	GameDate    time.Time   `json:"game_date"`
	Won         interface{} `json:"won"`
	GuessesUsed int64       `json:"guesses_used"`
}

func (q *Queries) GetUserGameHistory(ctx context.Context, userID int32) ([]GetUserGameHistoryRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserGameHistory, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserGameHistoryRow
	for rows.Next() {
		var i GetUserGameHistoryRow
		if err := rows.Scan(
			&i.GameID,
			&i.GameDate,
			&i.Won,
			&i.GuessesUsed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
