// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type CareerStat struct {
	PLAYERID         int64           `json:"PLAYER_ID"`
	SEASONID         string          `json:"SEASON_ID"`
	LEAGUEID         sql.NullString  `json:"LEAGUE_ID"`
	TEAMID           int64           `json:"TEAM_ID"`
	TEAMABBREVIATION sql.NullString  `json:"TEAM_ABBREVIATION"`
	PLAYERAGE        sql.NullFloat64 `json:"PLAYER_AGE"`
	GP               sql.NullInt64   `json:"GP"`
	GS               sql.NullInt64   `json:"GS"`
	MIN              sql.NullInt64   `json:"MIN"`
	FGM              sql.NullInt64   `json:"FGM"`
	FGA              sql.NullInt64   `json:"FGA"`
	FGPCT            sql.NullFloat64 `json:"FG_PCT"`
	FG3M             sql.NullInt64   `json:"FG3M"`
	FG3A             sql.NullInt64   `json:"FG3A"`
	FG3PCT           sql.NullFloat64 `json:"FG3_PCT"`
	FTM              sql.NullInt64   `json:"FTM"`
	FTA              sql.NullInt64   `json:"FTA"`
	FTPCT            sql.NullFloat64 `json:"FT_PCT"`
	OREB             sql.NullInt64   `json:"OREB"`
	DREB             sql.NullInt64   `json:"DREB"`
	REB              sql.NullInt64   `json:"REB"`
	AST              sql.NullInt64   `json:"AST"`
	STL              sql.NullInt64   `json:"STL"`
	BLK              sql.NullInt64   `json:"BLK"`
	TOV              sql.NullInt64   `json:"TOV"`
	PF               sql.NullInt64   `json:"PF"`
	PTS              sql.NullInt64   `json:"PTS"`
	PLAYERNAME       sql.NullString  `json:"PLAYER_NAME"`
}

type DailyGame struct {
	ID        int32     `json:"id"`
	PlayerID  int32     `json:"player_id"`
	GameDate  time.Time `json:"game_date"`
	CreatedAt time.Time `json:"created_at"`
}

type Guess struct {
	ID          int32     `json:"id"`
	UserID      int32     `json:"user_id"`
	DailyGameID int32     `json:"daily_game_id"`
	Guess       string    `json:"guess"`
	IsCorrect   bool      `json:"is_correct"`
	CreatedAt   time.Time `json:"created_at"`
}

type User struct {
	ID        int32     `json:"id"`
	Username  string    `json:"username"`
	Email     string    `json:"email"`
	Password  string    `json:"password"`
	CreatedAt time.Time `json:"created_at"`
}
