// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CreateDailyGame(ctx context.Context, playerID int32) (DailyGame, error)
	CreateGuess(ctx context.Context, arg CreateGuessParams) (Guess, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetAllPlayerNames(ctx context.Context) ([]GetAllPlayerNamesRow, error)
	GetDailyGameByID(ctx context.Context, id int32) (DailyGame, error)
	GetGuessCount(ctx context.Context, arg GetGuessCountParams) (int64, error)
	GetGuessesByUserAndGame(ctx context.Context, arg GetGuessesByUserAndGameParams) ([]Guess, error)
	GetPlayerByID(ctx context.Context, playerID int64) (GetPlayerByIDRow, error)
	GetPlayerCareerPath(ctx context.Context, playerID int64) ([]GetPlayerCareerPathRow, error)
	GetRandomPlayer(ctx context.Context) (GetRandomPlayerRow, error)
	GetTodayGame(ctx context.Context) (DailyGame, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id int32) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetUserGameHistory(ctx context.Context, userID int32) ([]GetUserGameHistoryRow, error)
	SearchPlayers(ctx context.Context, lower string) ([]SearchPlayersRow, error)
}

var _ Querier = (*Queries)(nil)
